---
IPAddr1: "10.1.1.1"
prefixlen: "24"
IPAddr2: "10.1.1.2"
route0: "10.1.1.0/24"
bond_interface: "bond100"
bridge: "br100"
vlanid: "100"
route1: "200.1.1.0/24"
route2: "201.1.1.0/24"
IPAddr3: "200.1.1.1"
IPAddr4: "200.1.1.2"
IPAddr5: "201.1.1.1"
IPAddr6: "201.1.1.2"
splitport: "4x1"
speed: "40g"
splitspeed: "10g"
#server_link: "ens192"
