---
IPAddr1: "10.1.1.1"
prefixlen: "24"
IPAddr2: "10.1.1.2"
bond_interface: "bond100"
bridge: "br100"
vlanid: "100"
route0: "10.1.1.0"
route1: "200.1.1.0"
IPAddr3: "200.1.1.1"
IPAddr4: "200.1.1.2"
IPAddr5: "201.1.1.1"
IPAddr6: "201.1.1.2"
fanin_speed: "100g"

