---
# vars file for img_install

set_eth0: |
  grep -q -F 'source-directory /etc/network/interfaces.d' /etc/network/interfaces || echo 'source-directory /etc/network/interfaces.d' >> /etc/network/interfaces
  grep -q -F 'nameserver' /etc/resolv.conf || echo 'nameserver {{nameserver}}' >> /etc/resolv.conf
  echo '' > /etc/network/interfaces.d/eth0
  ifconfig eth0 0.0.0.0
  echo "auto eth0" >> /etc/network/interfaces.d/eth0
  echo " iface eth0 inet static" >> /etc/network/interfaces.d/eth0
  echo " address {{ansible_host}}" >> /etc/network/interfaces.d/eth0
  echo " netmask {{ansible_host_netmask}}" >> /etc/network/interfaces.d/eth0
  echo " gateway {{ansible_host_gateway}}" >> /etc/network/interfaces.d/eth0
  echo " dns-nameservers 8.8.8.8" >> /etc/network/interfaces.d/eth0
  service networking restart
  ip route add default via {{ ansible_host_gateway }}
  ifconfig eth0
grub_boot_onie: |
  ln -sf /mnt/boot/grub /boot/grub
  grub-reboot $(( $( grep menuentry /boot/grub/grub.cfg | grep -n ONIE | cut -d: -f 1 ) - 1 ))
get_onie_prompt:
  'Info: ': "onie-discovery-stop"
  'ONIE:/ #': "\x07c\n"
set_onie_eth0: |
  onie-discovery-stop
  sleep 3
  ps | grep {networking.sh} | awk '{print $1}' | xargs kill -9
  sleep 3
  echo 'nameserver 10.14.1.1' > /etc/resolv.conf
  echo 'search force10networks.com' >> /etc/resolv.conf
  ifconfig eth0 {{ ansible_host }} netmask {{ ansible_host_netmask }} up
  route add default gateway {{ ansible_host_gateway }}
  ifconfig eth0
  ip route add default via {{ ansible_host_gateway }}
  route -n
nos_install: |
  onie-nos-install {{ image|default('http://archive.openswitch.net/installers/3.1.0/Dell-EMC/PKGS_OPX-3.1.0-installer-x86_64.bin') }}
